# Generated by Django 6.0.8 on 2026-10-01 11:05

import apps.candidates.models
import apps.candidates.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, help_text='e.g. Backend Engineer', max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, upload_to=apps.candidates.models.resume_upload_path, validators=[apps.candidates.validators.validate_resume])),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('open_to_work', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='candidates', to='jobs.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
